In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver
from selenium.webdriver.common.by import By

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

# Q1

Scrape the details of most viewed videos on YouTube from Wikipedia.            
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos           
You need to find following details:        
A) Rank    
B) Name    
C) Artist      
D) Upload date     
E) Views

In [2]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/1757872499.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [3]:
#creating an empty list
rank_list = []
name_list = []
artist_list = []
uploading_date_list = []
views_list = []


#scraping rank of the most viewed video
try:
    rank = driver.find_elements(by=By.XPATH, 
                                value="//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in rank:
        rank_list.append(i.text)
except NoSuchElementException:
    rank_list.append('-')
    
time.sleep(1)
#scraping name of the video
try:
    name = driver.find_elements(by=By.XPATH, 
                                value="//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in name:
        name_list.append(i.text)
except NoSuchElementException:
    name_list.append('-')

time.sleep(1)
#scraping artist name
try:
    artist = driver.find_elements(by=By.XPATH, 
                                  value="//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artist:
        artist_list.append(i.text)
except NoSuchElementException:
    artist_list.append('-')
    
time.sleep(1)
#scraping uploading date of the video
try:
    date = driver.find_elements(by=By.XPATH, 
                                value="//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in date:
        uploading_date_list.append(i.text)
except NoSuchElementException:
    uploading_date_list.append('-')
    
time.sleep(1)
#scraping no of views
try:
    views = driver.find_elements(by=By.XPATH, 
                                 value="//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views:
        views_list.append(i.text)
except NoSuchElementException:
    views_list.append('-')
    
time.sleep(2)    
# Make dataframe
df = pd.DataFrame({'Rank':rank_list,
                   'Video Name':name_list,
                   'Artist':artist_list,
                   'Upload Date':uploading_date_list,
                   'Views(billions)':views_list})
df

,Rank,Video Name,Artist,Upload Date,Views(billions)
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.80
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.87
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.37
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.74
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.54
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.44
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.67
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.60
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.58
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.50
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.45
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.12
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",3.95
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.71
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.60
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.59
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.55
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.46
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.38
19,20.,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.30
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.29
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.29
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.26
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.24
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.22
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.22
26,27.,"""Perfect""[45]",Ed Sheeran,"November 9, 2017",3.18
27,28.,"""Shake It Off""[46]",Taylor Swift,"August 18, 2014",3.18
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.16
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.09

# Q2

Scrape the details team India’s international fixtures from bcci.tv.       
Url = https://www.bcci.tv/              
You need to find following details:           
A) Match title (I.e. 1st ODI)     
B) Series      
C) Place      
D) Date      
E) Time     
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [4]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "https://www.bcci.tv/"
driver.get(url)
time.sleep(2)

#clicking the fixtures icon
button=driver.find_element(by=By.XPATH, 
                                 value="//ul[@class='nav navbar-nav  align-items-center']/li[2]/a")
driver.get(button.get_attribute("href"))
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/1685822076.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [5]:
#creating an empty list
match_title_list = []
series_list = []
place_list = []
date_list = []
time_list = []


#scraping title of the match    
try:
    title = driver.find_elements(by=By.XPATH, 
                                 value="//div[@class='fix-place ng-binding ng-scope']/span[1]")
    for i in title:
        match_title_list.append(i.text.replace("-"," "))
except NoSuchElementException:
    match_title_list.append('-')
    
time.sleep(1)
#scraping series of the match
try:
    series = driver.find_elements(by=By.XPATH, 
                                 value="//div[@class='fixture-card-main col-lg-3 col-md-6 col-sm-12 ng-scope']/div/div/h5[2]/span")
    for i in series:
        series_list.append(i.text)
except NoSuchElementException:
    series_list.append('-')

time.sleep(1)
#scraping place of the match
try:
    place = driver.find_elements(by=By.XPATH, 
                                 value="//div[@class='fix-place ng-binding ng-scope']")
    for i in place:
        place_list.append(i.text.split("-")[1])
except NoSuchElementException:
    place_list.append('-')
    
time.sleep(1)
#scraping date of the match
try:
    date = driver.find_elements(by=By.XPATH, 
                                 value="//div[@class='fixture-card-main col-lg-3 col-md-6 col-sm-12 ng-scope']/div/div/div/div[1]/h5")
    for i in date:
        date_list.append(i.text)
except NoSuchElementException:
    date_list.append('-')
    
time.sleep(1)
#scraping time of the match
try:
    match_time = driver.find_elements(by=By.XPATH, 
                                 value="//div[@class='fixture-card-main col-lg-3 col-md-6 col-sm-12 ng-scope']/div/div/div/div[2]/h5")
    for i in match_time:
        time_list.append(i.text)
except NoSuchElementException:
    time_list.append('-')
    
time.sleep(2)    
# Make dataframe
df = pd.DataFrame({'Match Title':match_title_list,
                   'Series':series_list,
                   'Place':place_list,
                   'Date':date_list,
                   'Time':time_list})
df

,Match Title,Series,Place,Date,Time
0,1st T20I,INDIA WOMEN TOUR OF SRI LANKA T20 SERIES 2022,"Rangiri Dambulla International Stadium, Dambulla",23 JUN 2022,2:00 AM PDT
1,2nd T20I,INDIA WOMEN TOUR OF SRI LANKA T20 SERIES 2022,"Rangiri Dambulla International Stadium, Dambulla",25 JUN 2022,2:00 AM PDT
2,1st T20I,INDIA TOUR OF IRELAND T20 SERIES 2022,"The Village, Dublin",26 JUN 2022,8:30 AM PDT
3,3rd T20I,INDIA WOMEN TOUR OF SRI LANKA T20 SERIES 2022,"Rangiri Dambulla International Stadium, Dambulla",27 JUN 2022,2:00 AM PDT
4,2nd T20I,INDIA TOUR OF IRELAND T20 SERIES 2022,"The Village, Dublin",28 JUN 2022,8:30 AM PDT
5,1st ODI,INDIA WOMEN TOUR OF SRI LANKA ODI SERIES 2022,"Pallekele International Cricket Stadium, Pall...",30 JUN 2022,9:30 PM PDT
6,5th Test,INDIA TOUR OF ENGLAND TEST SERIES 2021,"Edgbaston, Birmingham",1 JUL 2022,3:00 AM PDT
7,2nd ODI,INDIA WOMEN TOUR OF SRI LANKA ODI SERIES 2022,"Pallekele International Cricket Stadium, Pall...",3 JUL 2022,9:30 PM PDT

# Q3

Scrape the details of selenium exception from guru99.com.      
Url = https://www.guru99.com/      
You need to find following details:      
A) Name      
B) Description      
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [6]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "https://www.guru99.com/"
driver.get(url)
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/580830132.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [7]:
#clicking on the selenium
sel= driver.find_element(by=By.XPATH, 
                                 value="//*[@id='java_technologies']/li[3]/a")
try:
    sel.click()
except ElementNotInteractableException:
    driver.get(sel.get_attribute('href'))

In [8]:
#clicking on Selenium Exception Handling list Tutorial Page link
exception_page_link= driver.find_element(by=By.XPATH, 
                                 value="/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a").get_attribute('href')
driver.get(exception_page_link)

In [9]:
# creating empty lists 
name_list = []
description_list = []

#scraping exceptions name
try:
    name=driver.find_elements(by=By.XPATH, 
                                 value="//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in name[1:]:
        name_list.append(i.text)
except NoSuchElementException:         
    name_list.append('-')

time.sleep(1)   
#scraping exceptions description
try:
    description=driver.find_elements(by=By.XPATH, 
                                 value="//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in description[1:]:
        description_list.append(i.text)
except NoSuchElementException:
    description_list.append('-')

time.sleep(1)
#making a dataframe
df=pd.DataFrame({"Exception name": name_list, 
                 "Exception description": description_list})
df

,Exception name,Exception description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# Q4

Scrape the details of State-wise GDP of India from statisticstime.com.               
Url = http://statisticstimes.com/          
You have to find following details:              
A) Rank             
B) State                   
C) GSDP(18-19)                       
D) GSDP(17-18)                          
E) Share(2017)                  
F) GDP($ billion)                           
Note: - From statisticstimes home page you have to reach to economy page through code.

In [10]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/3615212987.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [11]:
#clicking on economy button
economy_button=driver.find_element(by=By.XPATH, 
                                 value="//div[@class='dropdown'][2]/div/a[3]")
driver.get(economy_button.get_attribute('href'))
time.sleep(2)

In [12]:
#clicking on GDP of Indian states
indian_states=driver.find_element(by=By.XPATH, 
                                 value="//ul[@style='list-style-type:none;margin-left:20px;']//li[1]/a")
try:
    indian_states.click()
except ElementNotInteractableException:
    driver.get(indian_states.get_attribute('href')) 
time.sleep(2)

In [13]:
#empty lists to store the data
rank_list = []
state_list = []
GSDP19_20 = []
GSDP18_19  = []
share_list = []
GDP_billion = []

#scraping the rank
try:
    rank=driver.find_elements(by=By.XPATH, 
                                 value="//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in rank:
        rank_list.append(i.text)
except NoSuchElementException:                
    rank_list.append('--')

time.sleep(1)
#scraping the States
try:
    states=driver.find_elements(by=By.XPATH, 
                                 value="//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
    for i in states:
        state_list.append(i.text)
except NoSuchElementException:
    state_list.append('--')

time.sleep(1)
#scraping GSDP(19-20)
try:
    gsdp1=driver.find_elements(by=By.XPATH, 
                                 value="//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in gsdp1:
        GSDP19_20.append(i.text)
except NoSuchElementException:    
    GSDP19_20.append('--')

    time.sleep(1)    
#scraping GSDP(18-19)
try:
    gsdp2=driver.find_elements(by=By.XPATH, 
                                 value="//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
    for i in gsdp2:
        GSDP18_19.append(i.text)
except NoSuchElementException:
    GSDP18_19.append('--')

time.sleep(1)
#scraping the share (18-19)
try:
    share=driver.find_elements(by=By.XPATH, 
                                 value="//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
    for i in share:
        share_list.append(i.text)
except NoSuchElementException:      
    share_list.append('--')

time.sleep(1)
#scraping GDP(in billion)
try:
    gdp=driver.find_elements(by=By.XPATH, 
                                 value="//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")
    for i in gdp:
        GDP_billion.append(i.text)
except NoSuchElementException:           
    GDP_billion.append('--')
time.sleep(1)

#Making dataframe
df=pd.DataFrame({'Rank':rank_list,
                'State':state_list,
                'GSDP(19-20)':GSDP19_20,
                'GSDP(18-19)':GSDP18_19,
                'Share(18-19)':share_list,
                'GDP($Billion)':GDP_billion})
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP($Billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# Q5

Scrape the details of trending repositories on Github.com.     
Url = https://github.com/     
You have to find the following details:     
A) Repository title     
B) Repository description     
C) Contributors count     
D) Language used     
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [14]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "https://github.com/"
driver.get(url)
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/592427396.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [15]:
# clicking the explore button
explore_button=driver.find_element(by=By.XPATH, 
                                 value="//ul[@class='d-lg-flex list-style-none']/li[4]/details/summary")
try:
    explore_button.click()
except:
    driver.get(explore_button.get_attribute('href'))
time.sleep(1)

#finding the trending option
trending_button=driver.find_element(by=By.XPATH, 
                                 value="//ul[@class='d-lg-flex list-style-none']/li[4]/details/div/ul/li[5]/a")
try:
    trending_button.click()
except:
    driver.get(trending_button.get_attribute('href'))
time.sleep(1)

In [16]:
#empty lists to store the data   
url_list=[]
repository_title=[]
repository_desc=[]
contributors_count=[]
language_list=[]


#scraping urls of repositories
repo_url=driver.find_elements(by=By.XPATH, 
                                 value="//h1[@class='h3 lh-condensed']/a")
for i in repo_url:
    url_list.append(i.get_attribute('href'))

time.sleep(1) 
#scraping title of repositories 
try:
    title=driver.find_elements(by=By.XPATH, 
                                 value="//h1[@class='h3 lh-condensed']")
    for i in title:
        repository_title.append(i.text)
except NoSuchElementException:
    repository_title.append('-')

time.sleep(1)

for i in url_list:
    driver.get(i)
    time.sleep(1)
    
    #scraping description of repositories
    try:
        description = driver.find_element(by=By.XPATH, 
                                 value="/html/body/div[4]/div/main/div[2]/div/div/div[3]/div[2]/div/div[1]/div/p")
        repository_desc.append(description.text)
    except NoSuchElementException:
        repository_desc.append('-')
    
    #scraping the contributors_count
    try:
        count=driver.find_element(by=By.XPATH, 
                                 value="//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        contributors_count.append(count.text)
    except NoSuchElementException:
        contributors_count.append('-')
    time.sleep(2)
    
     #scraping used languages
    lang=[]
    languages=driver.find_elements(by=By.XPATH, 
                                 value="//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            lang.append(i.text)
    else:
        lang.append('--')
    language_list.append(lang)
    
    
time.sleep(1)   
#Making dataframe
df=pd.DataFrame({'Repository Title':repository_title,
                'Repository Description':repository_desc,
                'Contributors Count':contributors_count,
                'Language Used':language_list})
df

,Repository Title,Repository Description,Contributors Count,Language Used
0,mingrammer / diagrams,🎨 Diagram as Code for prototyping cloud system...,104,"[Python, JavaScript]"
1,hashicorp / nomad,"Nomad is an easy-to-use, flexible, and perform...",556,"[Go, JavaScript, Handlebars, HCL, SCSS, Shell]"
2,facebook / lexical,Lexical is an extensible text editor framework...,97,"[TypeScript, JavaScript, HTML, CSS, Java, Shel..."
3,girliemac / a-picture-is-worth-a-1000-words,I am trying to describe complex matters in sim...,2,[--]
4,WenchaoD / FSCalendar,"A fully customizable iOS calendar library, com...",22,"[Objective-C, Swift, Ruby]"
5,PrefectHQ / prefect,The easiest way to automate your data,311,[Python]
6,Reiten966 / Polyformer,Polyformer is an open-source project that aims...,3,[--]
7,hashicorp / hcl,HCL is the HashiCorp configuration language.,72,"[Go, Ragel, Ruby, Perl, Python, HCL]"
8,pittcsc / Summer2023-Internships,Collection of Summer 2023 tech internships!,219,[Python]
9,Technawi / SOC-Analyst-Diploma,-,-,[--]
10,apache / hbase,Apache HBase,377,"[Java, Ruby, Perl, Shell, Python, Thrift]"
11,codeedu / imersao8,-,2,"[TypeScript, Go, JavaScript, Shell, Dockerfile]"
12,go-gorm / gorm,"The fantastic ORM library for Golang, aims to ...",305,"[Go, Shell]"
13,elixir-ecto / ecto,A toolkit for data mapping and language integr...,662,"[Elixir, Earthly]"
14,milvus-io / milvus,Vector database for scalable similarity search...,183,"[Go, Python, C++, Shell, Groovy, CMake]"
15,knative / serving,"Kubernetes-based, scale-to-zero, request-drive...",242,"[Go, Shell]"
16,Azure / azure-sdk-for-java,This repository is for active development of t...,454,"[Java, Groovy, Scala, PowerShell, Python, Jupy..."
17,Alamofire / Alamofire,Elegant HTTP Networking in Swift,240,[Swift]
18,OAI / OpenAPI-Specification,The OpenAPI Specification Repository,198,"[JavaScript, Shell, CSS, HTML]"
19,terraform-aws-modules / terraform-aws-alb,Terraform module to create an AWS Application/...,49,[HCL]
20,google / googletest,GoogleTest - Google Testing and Mocking Framework,356,"[C++, Python, CMake]"
21,fastlane / fastlane,🚀 The easiest way to automate building and rel...,"1,221","[Ruby, Swift, HTML, Objective-C, Java, Shell]"
22,sourcegraph / sourcegraph,Universal code search (self-hosted),274,"[Go, TypeScript, SCSS, PLpgSQL, Shell, Rust]"
23,woocommerce / woocommerce,"A customizable, open-source eCommerce platform...","1,165","[PHP, JavaScript, CSS, TypeScript, SCSS, Shell]"
24,firebase / firebase-ios-sdk,Firebase iOS SDK,177,"[Objective-C, C++, Swift, Objective-C++, C, Py..."

# Q6

Scrape the details of top 100 songs on billiboard.com.      
Url = https:/www.billboard.com/     
You have to find the following details:       
A) Song name      
B) Artist name     
C) Last week rank      
D) Peak rank         
E) Weeks on board         
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [17]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "http://www.billboard.com/"
driver.get(url)
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/3620663413.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [18]:
#clicking on Hot 100 
hot100=driver.find_element(by=By.XPATH, 
                                 value="//li[@class='o-nav__list-item '][1]/a")
try:
    hot100.click()
except ElementNotInteractableException:
    driver.get(hot100.get_attribute('href'))
time.sleep(2)

In [19]:
#empty lists to store the data
song_name_list=[]
artist_name_list=[]
last_week_Rank=[]
peak_rank=[]
weeks_on_board=[]

#scraping name of the song
try:
    name=driver.find_elements(by=By.XPATH, 
                                 value="//li[@class='lrv-u-width-100p']/ul/li/h3")
    for i in name:
        song_name_list.append(i.text)
except NoSuchElementException: 
    song_name_list.append('-')

time.sleep(1)    
#scraping name of the artist 
try:
    artist=driver.find_elements(by=By.XPATH, 
                                 value="//li[@class='lrv-u-width-100p']/ul/li[1]/span")
    for i in artist:
        artist_name_list.append(i.text)
except NoSuchElementException:    
    artist_name_list.append('--')

time.sleep(1)
#scraping last week rank
try:
    rank=driver.find_elements(by=By.XPATH, 
                                 value="//li[@class='lrv-u-width-100p']/ul/li[4]/span")
    for i in rank:
        last_week_Rank.append(i.text)
except NoSuchElementException:   
    last_week_Rank.append('--') 
    
time.sleep(1)
#scraping the peak rank the song reached
try:
    peak=driver.find_elements(by=By.XPATH, 
                                 value="//li[@class='lrv-u-width-100p']/ul/li[5]/span")
    for i in peak:
        peak_rank.append(i.text)
except NoSuchElementException:  
    peak_rank.append('--')

time.sleep(1)
#scraping the number of weeks on charts
try:
    week=driver.find_elements(by=By.XPATH, 
                                 value="//li[@class='lrv-u-width-100p']/ul/li[6]/span")
    for i in week:
        weeks_on_board.append(i.text)
except NoSuchElementException:      
    weeks_on_board.append('--')

time.sleep(1)
#making the dataframe
df=pd.DataFrame({'Song Name':song_name_list,
                'Artist':artist_name_list,
                'Last Week Rank':last_week_Rank,
                'Peak':peak_rank,
                'Weeks on Board':weeks_on_board})
df

,Song Name,Artist,Last Week Rank,Peak,Weeks on Board
0,As It Was,Harry Styles,1,1,11
1,First Class,Jack Harlow,2,1,10
2,Wait For U,Future Featuring Drake & Tems,3,1,7
3,About Damn Time,Lizzo,5,4,9
4,Running Up That Hill (A Deal With God),Kate Bush,4,4,23
...,...,...,...,...,...
95,Plan B,Megan Thee Stallion,95,29,4
96,Tomorrow Me,Luke Combs,-,61,2
97,Potion,"Calvin Harris, Dua Lipa & Young Thug",87,71,3
98,New Truck,Dylan Scott,-,99,1
99,Wrapped Around Your Finger,Post Malone,47,47,2

# Q7

Scrape the details of Data science recruiters from naukri.com.        
Url = https://www.naukri.com/             
You have to find the following details:            
A) Name              
B) Designation            
C) Company                
D) Skills they hire for               
E) Location            
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [20]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "https://www.naukri.com"
driver.get(url)
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/1547067302.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [21]:
#clicking on recruiters option
recuiters_tag=driver.find_element(by=By.XPATH, 
                                 value="/html/body/div[1]/div/div/ul/li[2]/a/div")
recuiters_tag.click()
driver.switch_to.window(driver.window_handles[-1]);

time.sleep(1)

In [22]:
#accesing search bar
search=driver.find_element(by=By.XPATH, 
                                 value="//div[@class='sWrap lftBrd']/div[2]/input")
search.send_keys("Data Science")
time.sleep(1)

#clicking on search button
search_button=driver.find_element(by=By.XPATH, 
                                 value="//button[@class='fl qsbSrch blueBtn']")
search_button.click()
time.sleep(1)

In [23]:
#empty lists to store the data
name_list = []
designation_list = []
company_list = []
skills_list = []
location_list = []

#scraping names
try:
    name=driver.find_elements(by=By.XPATH, 
                                 value="//span[@class='fl ellipsis']")
    for i in name:
        name_list.append(i.text)
except NoSuchElementException:       
    name_list.append('-')

time.sleep(1)
#scraping designation
try:
    designation=driver.find_elements(by=By.XPATH, 
                                 value="//span[@class='ellipsis clr']")
    for i in designation:
        designation_list.append(i.text)
except NoSuchElementException:     
    designation_list.append('-')

time.sleep(1)
#scraping names of company
try:
    company=driver.find_elements(by=By.XPATH, 
                                 value="//div[@class='recInfo']/div/p/a[2]")
    for i in company:
        company_list.append(i.text)
except NoSuchElementException:
    company_list.append('-')
    
time.sleep(1)
#scraping skills required
try:
    skills=driver.find_elements(by=By.XPATH, 
                                 value="//div[@class='recInfo']/div[2]")
    for i in skills:
        skills_list.append(i.text)
except NoSuchElementException:  
    skills_list.append('-')

time.sleep(1)       
#scraping location
soup=BeautifulSoup(driver.page_source,'html.parser')
location=soup.find_all('div',class_={'vcard'})
for i in location:
    try:
        location_list.append(i.text)
    except NoSuchElementException:
        location_list.append("-")
time.sleep(1)
        
#creating dataframe
df=pd.DataFrame({'Name':name_list,
                'Designation':designation_list,
                'Company':company_list,
                'Skills/Roles I hire for':skills_list,
                'Location':location_list})
df

,Name,Designation,Company,Skills/Roles I hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit HR Manager Data Science Netw...
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",shravan Kumar Gaddam Company Recruiter Sh...
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",MARSIAN Technologies LLP Company HR MARSI...
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Anik Agrawal Company Recruiter Enerlytics...
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",subhas patel Founder CEO LibraryXProject ...
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Abhishek - Only Analytics Hiring - India ...
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Institute for Financial Management and Re...
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Balu Ramesh HR Administrator Techvantage ...
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Asif Lucknowi Director Weupskill- Live Wi...
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",InstaFinancials Human Resource CBL Data S...
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Priyanka Akiri HR Manager Infinitive Soft...
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Kalpana Dumpala Executive Hiring Innomind...
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Mubarak Company HR MoneyTap Bengaluru / B...
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Kushal Rastogi Company HR QuantMagnum Tec...
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Mahesh Babu Channa HR Team Lead SocialPra...
15,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Ruchi Dhote Senior Executive Talent Acqui...
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Kapil Devang HR Manager BISP Solutions Bh...
17,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Rithika dadwal HR Recruiter Affine Analyt...
18,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Sakshi Chhikara Assistant Manager HR BIZ ...
19,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Sandhya Khandagale HR Recruiter Compumatr...
20,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Azahar Shaikh Company Recruiter NEAL ANAL...
21,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Manisha Yadav HR Executive Easi Tax Navi ...
22,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Riya Rajesh Manager Talent Acquisition No...
23,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Rashmi Bhattacharjee HR Head AXESTRACK SO...
24,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Faizan Kareem HR MANAGER FirstTech Consal...
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Shaun Rao Manager Human Resources Exela T...
26,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Dhruv Dev Dubey Company Recruitment Head ...
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Manas Lead Talent acquisition Autumn Leaf...
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",kumar Proprietor trainin Bengaluru / Bang...
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Sunil Vedula CEO Nanoprecise Sci Corp
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Rajat Kumar Founder CEO R.S Consultancy &...
31,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Rutuja Pawar Technical Recruiter Demand M...
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Jayanth N Project Manager Dollarbird Info...
33,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Avodha Business Development Associate Nik...
34,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",SREEDHAR Recruitment Consultant JOBSMILL ...
35,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Priya Khare Senior Manager Independent Co...
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Amit Sharma Consultant ASCO consulting Ne...
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Kanan senior technology instructor NY INS...
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Shashikant Chaudhary HR Recruiter/HR Excu...
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering","Brad Manager, Technical Recruiting O.C. T..."
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Madhusudhan Sridhar Erp Implementer MADHU...
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Ankit Sinha Head Analytics Suntech Global...
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Gaurav Chouhan Chief Technical Officer St...
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Rashi Kacker Sr Product Manager Impel Lab...
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Ashwini Director Global Delivery MRP Advi...
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Balaji Kolli Co Founder Saras Solutions I...
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Rajani Nagaraj HR Manager WildJasmine Ben...
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",ROHIT Kumar Architect LNT Private Limited...
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Amir Chowdhury Managing Partner Granular....
49,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Walmart Interra Skeps Expressstores indifi whi...,Ravi Dubey Recruitment Manager HyrEzy Tal...

# Q8

Scrape the details of Highest selling novels.     
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/   
You have to find the following details:    
A) Book name    
B) Author name    
C) Volumes sold     
D) Publisher     
E) Genre

In [24]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
driver.get(url)
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/838255578.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [25]:
#empty lists to store the data
book_name_list = []
author_name_list = []
volume_sold = []
publisher_list = []
genre_list = []

# Scraping Book name
try:
    for i in driver.find_elements(by=By.XPATH, value="//div[@class='embed block']/table/tbody/tr/td[2]"):
        book_name_list.append(i.text)
except NoSuchElementException:
    book_name_list.append("-")

time.sleep(1)
# Scraping Author name    
try:
    for i in driver.find_elements(by=By.XPATH, value="//div[@class='embed block']/table/tbody/tr/td[3]"):
        author_name_list.append(i.text)
except NoSuchElementException:
    author_name_list.append("-")

time.sleep(1)
# Scraping Volume sold
try: 
    for i in driver.find_elements(by=By.XPATH, value="//div[@class='embed block']/table/tbody/tr/td[4]"):
        volume_sold.append(i.text)
except NoSuchElementException:
    volume_sold.append("-")

time.sleep(1)
# Scraping the Publishers
try:
    for i in driver.find_elements(by=By.XPATH, value="//div[@class='embed block']/table/tbody/tr/td[5]"):
        publisher_list.append(i.text)
except NoSuchElementException:
    publisher_list.append("-")
    
time.sleep(1)
#Scraping Genre
try: 
    for i in driver.find_elements(by=By.XPATH, value="//div[@class='embed block']/table/tbody/tr/td[6]"):
        genre_list.append(i.text)
except NoSuchElementException:
    genre_list.append("-")

time.sleep(1)
# Making the dataframe 
df=pd.DataFrame({'Book Name': book_name_list,
                    'Author Name': author_name_list,
                    'Volume Sold': volume_sold,
                    'Publisher': publisher_list,
                    'Genre' : genre_list})
df

,Book Name,Author Name,Volume Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Q9

Scrape the details most watched tv series of all time from imdb.com.    
Url = https://www.imdb.com/list/ls095964455/    
You have to find the following details:    
A) Name       
B) Year span     
C) Genre     
D) Run time      
E) Ratings      
F) Votes

In [26]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "https://www.imdb.com/list/ls095964455/"
driver.get(url)
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/2552451669.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [27]:
#empty lists to store the data
name_list = []
year_span_list = []
genre_list = []
runtime_list = []
ratings_list = []
votes_list = []


# Scraping the series name
try:
    for i in driver.find_elements(by=By.XPATH, value="//h3[@class='lister-item-header']/a"):
        name_list.append(i.text)
except NoSuchElementException:
    name_list.append("-")
    
time.sleep(1)
# Scraping year span    
try:
    for i in driver.find_elements(by=By.XPATH, value="//h3[@class='lister-item-header']/span[2]"):
        year_span_list.append(i.text)
except NoSuchElementException:
    year_span_list.append("-")
    
time.sleep(1)
# Scraping Genre    
try:
    for i in driver.find_elements(by=By.XPATH, value="//div[@class='lister-item-content']/p/span[5]"):
        genre_list.append(i.text)
except NoSuchElementException:
    genre_list.append("-")
    
time.sleep(1)
#Scraping Runtime
try:
    for i in driver.find_elements(by=By.XPATH, value="//div[@class='lister-item-content']/p/span[3]"):
        runtime_list.append(i.text)
except NoSuchElementException:
    runtime_list.append("-") 

time.sleep(1)
#Scraping movie ratings
try:
    for i in driver.find_elements(by=By.XPATH, value="//div[@class='ipl-rating-widget']/div[1]/span[2]"):
        ratings_list.append(i.text)
except NoSuchElementException:
    ratings_list.append("-")

time.sleep(1)
# Scraping no.of votes
try:
    for i in driver.find_elements(by=By.XPATH, value="//div[@class='lister-item-content']/p[4]/span[2]"):
        votes_list.append(i.text)
except NoSuchElementException:
    votes_list.append("-")

time.sleep(1)
# making a dataframe 
df=pd.DataFrame({'Name':name_list,
                 'Year Span':year_span_list,
                 'Genre':genre_list,
                 'Run-Time':runtime_list,
                 'Ratin':ratings_list,
                 'Votes':votes_list})
df

,Name,Year Span,Genre,Run-Time,Ratin,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,998,347"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,046,388"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"950,939"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"284,213"
4,The 100,(2014– ),"Drama, Mystery, Sci-Fi",43 min,7.6,"244,006"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.4,"48,938"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,649"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"190,888"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,377"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"229,413"

# Q10

Details of Datasets from UCI machine learning repositories.     
Url = https://archive.ics.uci.edu/            
You have to find the following details:             
A) Dataset name           
B) Data type           
C) Task                 
D) Attribute type            
E) No of instances           
F) No of attribute         
G) Year            
Note: - from the home page you have to go to the ShowAllDataset page through code

In [28]:
#Lets first connect to the web driver
driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")
time.sleep(3)

#url from which you want to scrap data
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

C:\Users\Jesica\AppData\Local\Temp/ipykernel_10088/995588531.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\web driver\chromedriver.exe")

In [29]:
#clicking on view all datasets option
view=driver.find_element(by=By.XPATH, value="//a[@href='datasets.php']")
view.click()
time.sleep(1)

In [30]:
#empty lists to store the data    
name_list=[]
type_list=[]
task_list=[]
attribute_list=[]
no_of_instance=[]
no_of_attribute=[]
year_list=[]

# Scraping name of the dataset
try:
    name=driver.find_elements(by=By.XPATH, 
                                 value="/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in name:     
        name_list.append(i.text)
except NoSuchElementException:
    name_list.append('-')

time.sleep(1)
# Scraping datatype
try:
    type=driver.find_elements(by=By.XPATH, 
                                 value="/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in type[1:]:
        type_list.append(i.text)
except NoSuchElementException:
    type_list.append('-')
    
time.sleep(1)
# Scraping default task
try:
    task=driver.find_elements(by=By.XPATH, 
                                 value="/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in task[1:]:
        task_list.append(i.text)
except NoSuchElementException:
    task_list.append('-')

time.sleep(1)
# Scraping type of attribute
try:
    attribute=driver.find_elements(by=By.XPATH, 
                                 value="/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attribute[1:]:
        attribute_list.append(i.text)
except NoSuchElementException:
    attribute_list.append('-')

time.sleep(1)
#Scraping no. of instances
try:
    instance=driver.find_elements(by=By.XPATH, 
                                 value="/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in instance[1:]:
        no_of_instance.append(i.text)
except NoSuchElementException:
    no_of_instance.append('-')
    
time.sleep(1)       
# Scraping no. of attributes
try:
    attribute=driver.find_elements(by=By.XPATH, 
                                 value="/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in attribute[1:]:
        no_of_attribute.append(i.text)
except NoSuchElementException:
    no_of_attribute.append('-')
    
# Scrapping the year details
try:
    year=driver.find_elements(by=By.XPATH, 
                                 value="/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in year[1:]:
        year_list.append(i.text)
except NoSuchElementException:
    year_list.append('-')
    
# Creating the dataframe
df=pd.DataFrame({"Dataset Name":name_list,
                 "Data Type":type_list,
                 "Default Task":task_list,
                 "Attribute Type":attribute_list, 
                 "No of Instances":no_of_instance,
                 "No of Attributes":no_of_attribute,
                 "Year":year_list})
df

,Dataset Name,Data Type,Default Task,Attribute Type,No of Instances,No of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021